.TH GPUPDATE 1
.
.SH NAME
gpoa \- utility to update and apply group policy settings
.
.SH SYNOPSYS
.B gpoa
.
.SH DESCRIPTION
.B gpoa
Fetches GPT files for designated user from AD instance and transforms
them into UNIX system settings.
.SS Options
.TP
\fB-h\fP
.TP
\fB--dc \fIDC\fP
.TP
\fB--nodomain\fP
.TP
\fB--target \fITARGET\fP
.TP
\fB--noupdate\fP
.TP
\fB--noplugins\fP
.TP
\fB--loglevel \fILOGLEVEL\fP
.
.SH "SEE ALSO"
.
.SH BUGS
Tons of it.

