.\" GPOA - GPO Applier for Linux
.\"
.\" Copyright (C) 2019-2020 BaseALT Ltd.
.\"
.\" This program is free software: you can redistribute it and/or modify
.\" it under the terms of the GNU General Public License as published by
.\" the Free Software Foundation, either version 3 of the License, or
.\" (at your option) any later version.
.\"
.\" This program is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public License
.\" along with this program.  If not, see <http://www.gnu.org/licenses/>.
.TH GPOA 1
.
.SH NAME
gpoa \- utility to update and apply group policy settings
.
.SH SYNOPSYS
.B gpoa
.
.SH DESCRIPTION
.B gpoa
Fetches GPT files for designated user from AD instance and transforms
them into UNIX system settings.
.SS Options
.TP
\fB-h\fP
Show help.
.TP
\fB--dc \fIDC\fP
Specify domain controller hostname FQDN to replicate GPTs from. May be
useful in case of default DC problems.
.TP
\fB--target \fITARGET\fP
.TP
\fB--noupdate\fP
Don't update settings.
.TP
\fB--noplugins\fP
Don't run plugins.
.TP
\fB--loglevel \fILOGLEVEL\fP
Set logging verbosity from 0 to 5.
.
.SH FILES
\fB/usr/sbin/gpoa\fR utility uses \fB/usr/share/local-policy/default\fR
directory as a source for settings of "Local Policy" to set some
behavioral defaults for machine in AD domain.
.
All data is located in \fB/var/cache/gpupdate\fR. Also domain GPTs are
taken from Samba's \fB/var/cache/samba\fR.
.
The configuration file for \fBgpoa\fP is located in
\fB/etc/gpupdate/gpupdate.ini\fP.
.
The settings read from Samba are stored in
\fB/var/cache/gpupdate/registry.sqlite\fR and "Local Policy" settings
read from \fB/usr/local/share/local-policy/default\fR are converted
into GPT and stored as \fB/var/cache/gpupdate/local-policy\fR.
.SH "SEE ALSO"
gpupdate(1) gpupdate-setup(1)
.SH BUGS
Tons of it. Report at \fBhttps://github.com/altlinux/gpupdate\fP.

